<?php
namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class CompanySettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // Company Information
            [
                'key'         => 'company_name',
                'value'       => 'Ipd-OPD System',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Official name of the hospital',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_description',
                'value'       => 'Ipd-OPD System is a leading healthcare provider committed to delivering exceptional medical care with compassion, innovation, and excellence. Our dedicated team of healthcare professionals works tirelessly to ensure the well-being of our patients and community.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Brief description of the hospital',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_mission',
                'value'       => 'To provide comprehensive, compassionate healthcare services that improve the health and well-being of our patients and community through excellence in medical care, education, and research.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Hospital mission statement',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_vision',
                'value'       => 'To be the leading healthcare provider in the region, recognized for our commitment to patient-centered care, medical innovation, and community health improvement.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Hospital vision statement',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_values',
                'value'       => 'Compassion, Excellence, Integrity, Innovation, and Community Service guide everything we do in our commitment to patient care and medical advancement.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Hospital core values',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_address',
                'value'       => '123 Medical Center Drive, Springfield, IL 62701, United States',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Complete hospital address',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_phone',
                'value'       => '+1 (555) 123-4567',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Main hospital phone number',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_emergency_phone',
                'value'       => '+1 (555) 911-0000',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Emergency contact number',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_email',
                'value'       => 'info@springfieldgeneral.com',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Main hospital email address',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_founded_year',
                'value'       => '1998',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Year the hospital was founded',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_patients_served',
                'value'       => '50000',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Number of patients served annually',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_doctors_count',
                'value'       => '150',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Total number of doctors',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_years_experience',
                'value'       => '25',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Years of healthcare experience',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_departments_count',
                'value'       => '20',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Total number of departments',
                'is_public'   => true,
                'is_active'   => true,
            ],

            // Company branding and invoice-related details for printing
            [
                'key'         => 'company_logo',
                'value'       => 'storage/company/logo.png',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Company logo path (storage path)',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_logo_small',
                'value'       => 'storage/company/logo-small.png',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Small company logo for invoice footer or POS receipts',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_tax_id',
                'value'       => 'TAX-123456789',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Company tax ID for invoices',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_vat',
                'value'       => 'VAT-987654321',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Company VAT registration for invoices',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_registration_number',
                'value'       => 'REG-000001',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Company registration number',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_footer_text',
                'value'       => 'Thank you for choosing our services. Payments are non-refundable.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Footer text to show on printed documents like invoices and receipts',
                'is_public'   => true,
                'is_active'   => true,
            ],

            // Leadership Information
            [
                'key'         => 'company_ceo_name',
                'value'       => 'Dr. Sarah Johnson',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Chief Executive Officer name',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_ceo_bio',
                'value'       => 'Dr. Sarah Johnson brings over 20 years of healthcare leadership experience, specializing in hospital administration and patient care innovation.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Brief biography of the CEO',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_cmo_name',
                'value'       => 'Dr. Michael Chen',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Chief Medical Officer name',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_cmo_bio',
                'value'       => 'Dr. Michael Chen oversees medical operations and quality assurance, ensuring the highest standards of patient care across all departments.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Brief biography of the CMO',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_cno_name',
                'value'       => 'Ms. Emily Rodriguez',
                'type'        => 'string',
                'group'       => 'company',
                'description' => 'Chief Nursing Officer name',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_cno_bio',
                'value'       => 'Ms. Emily Rodriguez leads our nursing staff and patient care services, maintaining excellence in nursing practice and patient safety.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Brief biography of the CNO',
                'is_public'   => true,
                'is_active'   => true,
            ],

            // History Information
            [
                'key'         => 'company_history_foundation',
                'value'       => 'Our hospital was founded with a vision to provide accessible, high-quality healthcare to our community. Starting as a small clinic, we have grown into a comprehensive medical center.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'History of the hospital foundation',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_history_expansion',
                'value'       => 'Major expansion phase with the addition of new departments, advanced medical equipment, and increased bed capacity to better serve our growing patient population.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'History of hospital expansion',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_history_innovation',
                'value'       => 'Embraced cutting-edge medical technology and established partnerships with leading research institutions to bring the latest treatments and procedures to our patients.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'History of medical innovation',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_history_today',
                'value'       => 'Today, we continue our commitment to excellence, serving thousands of patients annually with compassion, innovation, and the highest standards of medical care.',
                'type'        => 'text',
                'group'       => 'company',
                'description' => 'Current status and achievements',
                'is_public'   => true,
                'is_active'   => true,
            ],

            // Business Hours
            [
                'key'         => 'business_hours_emergency_weekdays',
                'value'       => '24/7',
                'type'        => 'string',
                'group'       => 'business_hours',
                'description' => 'Emergency services hours on weekdays',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'business_hours_emergency_weekends',
                'value'       => '24/7',
                'type'        => 'string',
                'group'       => 'business_hours',
                'description' => 'Emergency services hours on weekends',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'business_hours_opd_weekdays',
                'value'       => '8:00 AM - 8:00 PM',
                'type'        => 'string',
                'group'       => 'business_hours',
                'description' => 'Outpatient department hours on weekdays',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'business_hours_opd_weekends',
                'value'       => '9:00 AM - 5:00 PM',
                'type'        => 'string',
                'group'       => 'business_hours',
                'description' => 'Outpatient department hours on weekends',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'business_hours_pharmacy_weekdays',
                'value'       => '8:00 AM - 10:00 PM',
                'type'        => 'string',
                'group'       => 'business_hours',
                'description' => 'Pharmacy hours on weekdays',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'business_hours_pharmacy_weekends',
                'value'       => '9:00 AM - 8:00 PM',
                'type'        => 'string',
                'group'       => 'business_hours',
                'description' => 'Pharmacy hours on weekends',
                'is_public'   => true,
                'is_active'   => true,
            ],

            // Social Media Links
            [
                'key'         => 'social_facebook',
                'value'       => 'https://facebook.com/springfieldgeneral',
                'type'        => 'string',
                'group'       => 'social',
                'description' => 'Facebook page URL',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'social_twitter',
                'value'       => 'https://twitter.com/springfieldgen',
                'type'        => 'string',
                'group'       => 'social',
                'description' => 'Twitter/X profile URL',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'social_instagram',
                'value'       => 'https://instagram.com/springfieldgeneral',
                'type'        => 'string',
                'group'       => 'social',
                'description' => 'Instagram profile URL',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'social_linkedin',
                'value'       => 'https://linkedin.com/company/springfield-general-hospital',
                'type'        => 'string',
                'group'       => 'social',
                'description' => 'LinkedIn company page URL',
                'is_public'   => true,
                'is_active'   => true,
            ],
            [
                'key'         => 'social_youtube',
                'value'       => 'https://youtube.com/@springfieldgeneral',
                'type'        => 'string',
                'group'       => 'social',
                'description' => 'YouTube channel URL',
                'is_public'   => true,
                'is_active'   => true,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(['key' => $setting['key']], $setting);
        }

        $this->command->info('Company settings seeded successfully!');
    }
}
