<?php

return [
    'otp_types' => [
        'register',
        'forgot_password',
    ],

    "register_otp_expiry" => 5, // in minutes
    "cache_duration" => 60, // in minutes
    "default_password" => 'nsl-monitoring', // default password for user

    "user_types" => [
        'super_admin' => 'super_admin',
        'admin' => 'admin',
        'user' => 'user',
        'customer' => 'customer',
        'seller' => 'seller',
        'manager' => 'manager',
        'delivery' => 'delivery',
        'staff' => 'staff',
        'driver' => 'driver',
        'rider' => 'rider',
        'agent' => 'agent',
        'merchant' => 'merchant',
        'employee' => 'employee',
        'doctor' => 'doctor',
    ],

    'account_types' => [
        'Cash',
        'Bank Account',
        'Card',
        'Mobile Banking',
        'Bank Cheque',
        'Others',
    ],
    'card_types' => [
        'Debit',
        'Credit',
        'master',
        'visa',
        'Amex',
        'Nexus',
        'Prepaid',
        'American Express',
        'Others',
    ],
    'bank_types' => [
        'Sonali Bank Limited',
        'Janata Bank Limited',
        'Agrani Bank Limited',
        'Rupali Bank Limited',
        'Pubali Bank Limited',
        'Uttara Bank Limited',
        'Dhaka Bank Limited',
        'Dutch-Bangla Bank Limited',
        'Brac Bank Limited',
        'Eastern Bank Limited',
        'Mercantile Bank Limited',
        'Mutual Trust Bank Limited',
        'National Bank Limited',
        'One Bank Limited',
        'Premier Bank Limited',
        'Prime Bank Limited',
        'South East Bank Limited',
        'Standard Bank Limited',
        'Trust Bank Limited',
        'United Commercial Bank Limited',
        'Bangladesh Commerce Bank Limited',
        'First Security Islami Bank Limited',
        'The City Bank Limited',
        'Bank Asia Limited',
        'Exim Bank Limited',
        'Islamic Bank Bangladesh Limited',
        'Shahjalal Islami Bank Limited',
        'Social Islami Bank Limited',
        'Al-Arafah Islami Bank Limited',
        'Jamuna Bank Limited',
        'Icb Islamic Bank Limited',
        'Shimanto Bank Limited',
        'NRB Bank Limited',
        'Meghna Bank Limited',
        'Midland Bank Limited',
        'Modhumoti Bank Limited',
        'Nagad Bank Limited',
        'NRB Commercial Bank Limited',
        'Padma Bank Limited',
        'Standard Chartered Bank Limited',
        'The Premier Bank Limited',
        'Union Bank Limited',
        'Woori Bank Limited',
        'Bank Alfalah Limited',
        'Citibank N.A. Bangladesh',
        'Commercial Bank of Ceylon Limited',
        'Habib Bank Limited',
        'HSBC Limited',
        'ICICI Bank Limited',
        'State Bank of India',
        'Bank of Tokyo-Mitsubishi UFJ Limited',
        'Citi Bank N.A. Bangladesh',
        'Others',
    ],
    'mobile_types' => [
        'Bkash',
        'Rocket',
        'Nagad',
        'SureCash',
        'Upay',
        'iPay',
        'mCash',
        'MyCash',
        'Others',
    ],

    "cache_key" => [
        'location' => [
            'locations_with_district_upazila' => 'locations_with_district_upazila',
            'division' => 'division',
            'district' => 'district',
            'upazila' => 'upazila',
        ]
    ],

    'APP_NAME' => env('APP_NAME', 'My Application'),
    'SUPPORT_EMAIL' => 'support@example.com',
    'MAX_UPLOAD_SIZE' => 2048, // in kilobytes
    'TIMEZONE' => 'Asia/Dhaka',
    'DEFAULT_LANGUAGE' => 'en',
];
