@extends('backend.layouts.master')

@section('title', 'Radiology Order Details')

@section('content')
    <div class="container-fluid">
        <div class="app-page-head d-flex flex-wrap gap-3 align-items-center justify-content-between">
            <div class="clearfix">
                <h1 class="app-page-title">Radiology Order Details</h1>
            </div>
            <div>
                <a href="{{ route('radiology.index') }}" class="btn btn-light">
                    <i class="bi bi-arrow-left me-1"></i> Back to List
                </a>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-12">
                <div class="card overflow-hidden">
                    <div class="card-header border-0 pb-0">
                        <h6 class="card-title mb-0">Order Info</h6>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped mb-3">
                            <tbody>
                                <tr>
                                    <th style="width:30%">Order Number</th>
                                    <td>{{ $order->order_number ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Date/Time</th>
                                    <td>{{ optional($order->datetime)->format('Y-m-d H:i') ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Patient</th>
                                    <td>{{ optional($order->patient)->patient_name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>MRN</th>
                                    <td>{{ optional($order->patient)->mrn ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Doctor</th>
                                    <td>{{ optional($order->doctor)->name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Source</th>
                                    <td>{{ $order->source ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Lab</th>
                                    <td>{{ $order->lab_name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Collected By</th>
                                    <td>{{ $order->collected_by ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Generated By</th>
                                    <td>{{ optional($order->generatedBy)->name ?? '-' }}</td>
                                </tr>
                                <tr>
                                    <th>Remarks</th>
                                    <td>{{ $order->remarks ?? '-' }}</td>
                                </tr>
                            </tbody>
                        </table>

                        <h6 class="fw-bold mb-2">Investigations</h6>
                        <div class="table-responsive">
                            <table class="table table-bordered mb-0">
                                <thead class="table-light">
                                    <tr>
                                        <th>#</th>
                                        <th>Investigation</th>
                                        <th>Short Name</th>
                                        <th>Category</th>
                                        <th>Type</th>
                                        <th>Status</th>
                                        <th>File</th>
                                        <th class="text-end">Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($order->requests as $r)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ optional($r->labInvestigation)->name ?? '-' }}</td>
                                            <td>{{ optional($r->labInvestigation)->short_name ?? '-' }}</td>
                                            <td>{{ optional($r->labInvestigationCategory)->name ?? '-' }}</td>
                                            <td>{{ optional($r->labInvestigationType)->name ?? '-' }}</td>
                                            <td style="min-width:160px;">
                                                @php
                                                    $statusOptions = ['Pending', 'Sample Collected', 'In Process', 'Completed', 'Result Ready'];
                                                    $currentStatus = $r->status ?? 'Pending';
                                                @endphp
                                                <select class="form-select form-select-sm js-status-select"
                                                    data-url="{{ route('radiology.requests.status.update', [$order->id, $r->id]) }}">
                                                    @foreach ($statusOptions as $opt)
                                                        <option value="{{ $opt }}" @selected($currentStatus === $opt)>{{ $opt }}</option>
                                                    @endforeach
                                                </select>
                                            </td>
                                            <td style="min-width:220px;">
                                                @if ($r->file)
                                                    <div class="d-flex align-items-center gap-2 mb-1">
                                                        <a href="{{ asset('storage/' . $r->file) }}" target="_blank"
                                                            class="btn btn-sm btn-outline-primary">
                                                            <i class="bi bi-eye"></i> View
                                                        </a>
                                                        <form action="{{ route('radiology.requests.file.delete', [$order->id, $r->id]) }}"
                                                            method="POST"
                                                            onsubmit="return confirm('Remove this file?');">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                                                <i class="bi bi-trash"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                @endif
                                                <form action="{{ route('radiology.requests.file.upload', [$order->id, $r->id]) }}"
                                                    method="POST" enctype="multipart/form-data"
                                                    class="d-flex align-items-center gap-1">
                                                    @csrf
                                                    <input type="file" name="file"
                                                        class="form-control form-control-sm"
                                                        accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" required>
                                                    <button type="submit" class="btn btn-sm btn-primary">
                                                        {{ $r->file ? 'Replace' : 'Upload' }}
                                                    </button>
                                                </form>
                                            </td>
                                            <td class="text-end">
                                                {{ optional($r->labInvestigation)->price !== null ? number_format((float) $r->labInvestigation->price, 2) : '-' }}
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="8" class="text-center">No investigations</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        (function () {
            const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '{{ csrf_token() }}';
            document.querySelectorAll('.js-status-select').forEach(function (select) {
                select.dataset.previous = select.value;
                select.addEventListener('change', function () {
                    const url = select.dataset.url;
                    const newStatus = select.value;
                    const previous = select.dataset.previous;
                    select.disabled = true;
                    fetch(url, {
                        method: 'PATCH',
                        headers: {
                            'Content-Type': 'application/json',
                            'Accept': 'application/json',
                            'X-CSRF-TOKEN': csrf,
                        },
                        body: JSON.stringify({ status: newStatus }),
                    })
                    .then(function (res) {
                        if (!res.ok) throw new Error('Failed to update status');
                        return res.json();
                    })
                    .then(function (data) {
                        select.dataset.previous = data.status || newStatus;
                    })
                    .catch(function () {
                        select.value = previous;
                        alert('Could not update status. Please try again.');
                    })
                    .finally(function () {
                        select.disabled = false;
                    });
                });
            });
        })();
    </script>
@endpush
